---
- name: create drop-ins dirs for systemd
  file:
    state: directory
    mode: 755
    path: "/etc/systemd/system/{{ item }}.d"
  with_items:
    - kresd.service
    - kresd.socket
    - kresd-tls.socket
  notify: restart kresd

- name: configure systemd for kresd
  template: src='configure.j2' dest='/etc/systemd/system/{{ item }}.d/ansible.conf'
  with_items:
    - kresd.service
    - kresd.socket
    - kresd-tls.socket
  notify: restart kresd

- name: configure kresd
  template: src='configure.j2' dest='/etc/knot-resolver/{{ item }}'
  with_items:
    - kresd.conf
  notify: restart kresd
